/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "device_settings.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DeviceSettingsProto, DeviceSettingsProto, AUTO)


PB_BIND(ComponentProto, ComponentProto, AUTO)



