/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_DEVICE_SETTINGS_PB_H_INCLUDED
#define PB_DEVICE_SETTINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ComponentProto {
    char name[17];
    char id[17];
    pb_size_t gpio_pin_count;
    int32_t gpio_pin[8];
} ComponentProto;

typedef struct _DeviceSettingsProto {
    char node_name[33];
    char mqtt_server_url[33];
    char time_zone[11];
    pb_callback_t component;
} DeviceSettingsProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceSettingsProto_init_default         {"", "", "", {{NULL}, NULL}}
#define ComponentProto_init_default              {"", "", 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define DeviceSettingsProto_init_zero            {"", "", "", {{NULL}, NULL}}
#define ComponentProto_init_zero                 {"", "", 0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define ComponentProto_name_tag                  1
#define ComponentProto_id_tag                    2
#define ComponentProto_gpio_pin_tag              3
#define DeviceSettingsProto_node_name_tag        1
#define DeviceSettingsProto_mqtt_server_url_tag  2
#define DeviceSettingsProto_time_zone_tag        3
#define DeviceSettingsProto_component_tag        4

/* Struct field encoding specification for nanopb */
#define DeviceSettingsProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_name,         1) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_server_url,   2) \
X(a, STATIC,   SINGULAR, STRING,   time_zone,         3) \
X(a, CALLBACK, REPEATED, MESSAGE,  component,         4)
#define DeviceSettingsProto_CALLBACK pb_default_field_callback
#define DeviceSettingsProto_DEFAULT NULL
#define DeviceSettingsProto_component_MSGTYPE ComponentProto

#define ComponentProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   id,                2) \
X(a, STATIC,   REPEATED, INT32,    gpio_pin,          3)
#define ComponentProto_CALLBACK NULL
#define ComponentProto_DEFAULT NULL

extern const pb_msgdesc_t DeviceSettingsProto_msg;
extern const pb_msgdesc_t ComponentProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceSettingsProto_fields &DeviceSettingsProto_msg
#define ComponentProto_fields &ComponentProto_msg

/* Maximum encoded size of messages (where known) */
/* DeviceSettingsProto_size depends on runtime parameters */
#define ComponentProto_size                      124

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
